### PR TITLE
Example page was always using default yaml data

### PR DESCRIPTION
**Pull request by garethfoote**

### CODE REVIEW

**Review by TomJKing — APPROVED** [review]
Looks good. Thanks

**Comment by garethfoote** [comment]
Hi @MancunianSam Did you sort out this issue in another way/branch or should we merge this one into main?

**Comment by TomJKing** [comment]
@garethfoote @MancunianSam Can this PR be merged, its been hanging around for a while now? Thanks

**Comment by garethfoote** [comment]
@TomJKing This has been superceded by another PR. It can be closed without merging.

**Pull request closed without merging**
